IF NOT EXISTS(SELECT loginname FROM syslogins WHERE loginname = '$(DB_USERNAME)')
  BEGIN
    CREATE LOGIN [$(DB_USERNAME)] WITH PASSWORD = '$(DB_PASSWORD)', CHECK_POLICY = OFF, DEFAULT_DATABASE = [$(DB_DATABASE)];
    USE [$(DB_DATABASE)];
    CREATE USER [$(DB_USERNAME)] FOR LOGIN [$(DB_USERNAME)];
    EXEC sp_addrolemember N'db_owner', N'$(DB_USERNAME)';
  END