IF NOT EXISTS(SELECT loginname FROM syslogins WHERE loginname = '$(PUBLIC_API_DB_NAME)')
  BEGIN
    CREATE LOGIN [$(DB_USERNAME)] WITH PASSWORD = '$(DB_PASSWORD)', CHECK_POLICY = OFF, DEFAULT_DATABASE = [$(PUBLIC_API_DB_NAME)];
    USE [$(PUBLIC_API_DB_NAME)];
    CREATE USER [$(DB_USERNAME)] FOR LOGIN [$(DB_USERNAME)];
    EXEC sp_addrolemember N'db_owner', N'$(DB_USERNAME)';
  END
